kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: panfactum-local

containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:35000"]
      endpoint = ["http://panfactum-local-control-plane:35000"]

nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      - containerPort: 35000
        hostPort: 35000
        protocol: TCP
  - role: worker
  - role: worker
  - role: worker
