name: Run Terraform Init
description: Runs terragrunt init for an directory tree
inputs:
  tg-directory:
    description: 'The directory in which to run "terragrunt run-all init"'
    required: true
runs:
  using: "composite"
  steps:
    - name: "Terragrunt init"
      run: 'terragrunt init --input=false -compact-warnings --terragrunt-non-interactive --terragrunt-include-external-dependencies --terragrunt-use-partial-parse-config-cache'
      working-directory: ${{ inputs.tg-directory }}
      shell: bash
