name: Run Terraform Apply (Single)
description: Runs terragrunt apply on a single module
inputs:
  tg-directory:
    description: 'The directory in which to run "terragrunt apply"'
    required: true
  target:
    description: 'The resource to target in the apply'
    required: false
  refresh:
    description: 'Whether to refresh the state or not'
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: "Setup credentials"
      uses: ./.github/actions/setup-tf-creds

    - name: "Terragrunt apply (module)"
      if: ${{ inputs.target == '' }}
      run: 'terragrunt apply --refresh=${{ inputs.refresh }} --input=false -auto-approve -compact-warnings --terragrunt-non-interactive --terragrunt-include-external-dependencies --terragrunt-fetch-dependency-output-from-state'
      working-directory: ${{ inputs.tg-directory }}
      shell: bash

    - name: "Terragrunt apply (target)"
      if: ${{ inputs.target  != '' }}
      run: 'terragrunt apply --refresh=${{ inputs.refresh }} --target ${{ inputs.target }} --input=false -auto-approve -compact-warnings --terragrunt-non-interactive --terragrunt-include-external-dependencies --terragrunt-fetch-dependency-output-from-state'
      working-directory: ${{ inputs.tg-directory }}
      shell: bash
