name: Run Terraform Apply
description: Runs terragrunt apply for an directory tree
inputs:
  tg-directory:
    description: 'The directory in which to run "terragrunt run-all"'
    required: true
  tg-init-directory:
    description: 'The directory in which to run "terragrunt init" to populate the plugin cache'
    required: true
runs:
  using: "composite"
  steps:
    - name: "Setup credentials"
      uses: ./.github/actions/setup-tf-creds

    - name: "Terragrunt init"
      uses: ./.github/actions/tf-init
      with:
        tg-init-directory: ${{inputs.tg-init-directory}}

    - name: "Terragrunt apply"
      run: 'terragrunt run-all apply --input=false -compact-warnings --terragrunt-non-interactive --terragrunt-include-external-dependencies --terragrunt-parallelism 4'
      working-directory: ${{inputs.tg-directory}}
      shell: bash
