name: Run Terraform Apply
description: Runs terragrunt apply for an directory tree
inputs:
  tg-directory:
    description: 'The directory in which to run "terragrunt run-all"'
    required: true
runs:
  using: "composite"
  steps:
    - name: "Setup credentials"
      uses: ./.github/actions/setup-tf-creds

    - name: "Terragrunt init"
      uses: ./.github/actions/tf-init
      with:
        tf-directory: ${{ inputs.tg-directory }}

    - name: "Terragrunt apply"
      run: 'terragrunt run-all apply --input=false -compact-warnings --terragrunt-non-interactive --terragrunt-include-external-dependencies --terragrunt-parallelism 10'
      working-directory: ${{ inputs.tg-directory }}
      shell: bash
      env:
        TERRAGRUNT_DOWNLOAD: "/home/runner/_work/.terragrunt-cache"
