name: Build Internal Docs Image
on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: development-small
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'

      - uses: ./.github/actions/build-image
        timeout-minutes: 15
        with:
          image-repo: internal-docs
          image-tag: ${{ github.sha }}
          containerfile-directory: packages/internal-docs

  apply-dev:
    runs-on: development-small
    if: ${{github.ref == 'refs/heads/main'}}
    timeout-minutes: 30
    concurrency:
      group: apply-dev-internal-docs
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/tf-apply-single
        with:
          tg-directory: ./environments/development/us-east-2/panfactum_internal_docs_deployment
          target: module.deployment
          refresh: "false"
