name: Build Internal Docs Image
on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: development-small
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'

      - uses: ./.github/actions/build-image
        timeout-minutes: 15
        with:
          image-repo: internal-docs
          image-tag: ${{ github.sha }}
          containerfile-directory: packages/internal-docs

      - uses: ./.github/actions/tf-apply-single
        if: ${{ github.ref }} == 'refs/heads/main'
        with:
          tg-directory: ./environments/development/us-east-2/panfactum_internal_docs_deployment
