name: Build Bastion Image
on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: development-small
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/build-image
        timeout-minutes: 15
        with:
          image-repo: "bastion"
          image-tag: ${{ github.sha }}
          containerfile-directory: packages/bastion
