name: Build Primary API Image
on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: development-medium
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/build-image
        timeout-minutes: 30
        with:
          image-repo: primary-api
          image-tag: ${{ github.sha }}
          containerfile-directory: packages/primary-api

      - uses: ./.github/actions/tf-apply-single
        if: ${{ github.ref }} == 'refs/heads/main'
        timeout-minutes: 30
        with:
          tg-directory: ./environments/development/us-east-2/panfactum_primary_api_deployment
