name: Build Bastion Image
on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: development-medium
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/build-image
        timeout-minutes: 15
        with:
          image-repo: "bastion"
          image-tag: ${{ github.sha }}
          containerfile-directory: packages/bastion

      - uses: ./.github/actions/tf-apply-single
        if: ${{ github.ref }} == 'refs/heads/main'
        timeout-minutes: 30
        with:
          tg-directory: ./environments/development/us-east-2/kube_ingress_controllers

