name: Build Bastion Image
on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: development-small
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/build-image
        timeout-minutes: 15
        with:
          image-repo: "bastion"
          image-tag: ${{ github.sha }}
          containerfile-directory: packages/bastion

  apply-dev:
    runs-on: development-small
    if: ${{ github.ref }} == 'refs/heads/main'
    timeout-minutes: 60
    concurrency:
      group: apply-dev-bastion
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/tf-apply-single
        with:
          tg-directory: ./environments/development/us-east-2/kube_ingress_controllers
