name: Build Internal Docs Image
on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: development-small
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: 'true'

      - uses: ./.github/actions/build-image
        timeout-minutes: 15
        with:
          image-repo: internal-docs
          image-tag: ${{ github.sha }}
          containerfile-directory: packages/internal-docs
