name: Build CI Image
on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  apply:
    runs-on: development-small
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/build-image
        with:
          image-repo: "ci"
          image-tag: ${{ github.sha }}
          containerfile-directory: packages/ci
