name: Build CI Image
on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: development-small
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-image
        timeout-minutes: 120
        with:
          image-repo: "ci"
          image-tag: ${{ github.sha }}
          containerfile-directory: packages/ci

  apply-dev:
    runs-on: development-small
    if: ${{ github.ref }} == 'refs/heads/main'
    timeout-minutes: 30
    concurrency:
      group: apply-dev-ci
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/tf-apply-single
        with:
          tg-directory: ./environments/development/us-east-2/kube_gha_arc_runners
          target: helm_release.runner
