name: Build Primary API Image
on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: development-small
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/build-image
        timeout-minutes: 30
        with:
          image-repo: primary-api
          image-tag: ${{ github.sha }}
          containerfile-directory: packages/primary-api

  apply-dev:
    runs-on: development-small
    if: ${{ github.ref }} == 'refs/heads/main'
    timeout-minutes: 30
    concurrency:
      group: apply-dev-primary-api
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/tf-apply-single
        with:
          tg-directory: ./environments/development/us-east-2/panfactum_primary_api_deployment
          target: module.deployment
