name: CNPG PDB Patch
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
defaults:
  run:
    shell: bash

concurrency:
  cancel-in-progress: false
  group: cnpg-pdb-patch

jobs:
  patch:
    strategy:
      matrix:
        environment: [ "development" ]
    runs-on: ${{ matrix.environment }}-small
    steps:
      - name: "Patch cluster PDBs"
        shell: bash
        run: 'cnpg-pdb-patch'
