name: Scale Down Buildkit
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'
defaults:
  run:
    shell: bash

concurrency:
  cancel-in-progress: false
  group: scale-down-buildkit

jobs:
  scale-down:
    runs-on: development-small
    steps:
      - name: "Scale down buildkit"
        shell: bash
        run: 'scale-buildkit --attempt-scale-down 3600'
