name: Test Runners (Development)
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  apply:
    runs-on: development-small
    steps:
      - name: "Test bash"
        run: echo 'Hello World!'

      - name: "Test terraform"
        run: terraform --version

      - name: "Test kubernetes interactions"
        run: kubectl cluster-info

      - name: "Test AWS interactions"
        run: aws sts get-caller-identity

      - name: "Test Vault token retrieval"
        run: echo "VAULT_TOKEN=$(vault write --format=json auth/kubernetes/login role=arc-runners jwt=@/var/run/secrets/kubernetes.io/serviceaccount/token | jq -r .auth.client_token)" >> $GITHUB_ENV

      - name: "Test Vault token"
        run: vault token capabilities /
