name: Test Runners (Development)
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: development-small
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: "Test bash"
        run: 'echo "Hello World!"'

      - name: "Test Github interactions"
        run: 'gh issue list -R Panfactum/panfactum'

      - name: "Test terraform"
        run: 'terraform --version'

      - name: "Test kubernetes interactions"
        run: 'kubectl cluster-info'

      - name: "Test AWS authentication"
        run: 'aws sts get-caller-identity'

      - name: "Test AWS authorization"
        run: 'aws s3 ls'

      - name: "Test Vault token retrieval"
        run: 'get-vault-token'

      - name: "Test Vault token"
        run: 'vault token capabilities /'

      - name: "Test AAD authentication"
        run: 'az login --allow-no-subscriptions --federated-token "$(cat /var/run/secrets/azure/tokens/azure-identity-token)" --service-principal -u "$AZURE_CLIENT_ID" -t "$AZURE_TENANT_ID"'

      - name: "Test AAD authorization"
        run: 'az ad app list | jq .[].displayName'


